"""Wiki MCP 1차 검증 스크립트.

서버: http://localhost:9102/mcp (이미 부팅된 컨테이너 가정)
대상 wiki: https://github.com/{GITHUB_TARGET_OWNER}/{GITHUB_TARGET_REPO}/wiki

검증 시퀀스:
  1. page.list             현 wiki 페이지 목록
  2. page.create           [verify] slug 로 새 페이지 작성
  3. page.get              라운드트립 (front matter parse 확인)
  4. page.list             만든 페이지 포함 확인
  5. page.update           content 변경 → 반영 확인
  6. page.count            전체 개수
  7. page.delete           정리 (영구 삭제)
"""

from __future__ import annotations

import asyncio
import sys
from datetime import UTC, datetime

from dev_team_shared.mcp_client import StreamableMCPClient
from dev_team_shared.wiki import (
    PageCreate,
    PageUpdate,
    WikiClient,
)


async def main() -> int:
    url = "http://localhost:9102/mcp"
    print(f"connecting to {url}...")

    async with await StreamableMCPClient.connect(url) as mcp:
        client = WikiClient(mcp)

        # 1. list (before)
        print("\n[1] page.list — before")
        before = await client.pages.list()
        print(f"    {len(before)} pages")
        for r in before:
            print(f"    - {r.slug} (title={r.title!r})")

        # 2. create
        slug = f"verify-{datetime.now(UTC).strftime('%Y%m%d-%H%M%S')}"
        print(f"\n[2] page.create — slug={slug!r}")
        created = await client.pages.create(
            PageCreate(
                slug=slug,
                title="[verify] sandbox page (auto)",
                content_md="# Auto Verify\n\nGenerated by mcp/wiki verify script.",
                page_type="prd",
                structured={"milestones": [{"name": "M1"}], "in_scope": ["x"]},
            ),
        )
        print(f"    created.title={created.title!r} page_type={created.page_type}")
        print(f"    structured={created.structured}")
        print(f"    timestamps: created={created.created_at}, updated={created.updated_at}")

        # 3. get round trip
        print("\n[3] page.get — round trip")
        fetched = await client.pages.get(slug)
        if fetched is None:
            print("    !! page.get returned None")
            return 1
        if fetched.title != created.title:
            print(f"    !! title mismatch: got {fetched.title!r}")
            return 1
        if fetched.page_type != "prd":
            print(f"    !! page_type mismatch: got {fetched.page_type!r}")
            return 1
        if fetched.structured != created.structured:
            print(f"    !! structured mismatch: got {fetched.structured}")
            return 1
        print("    round trip OK (title / page_type / structured 일치)")

        # 4. list — 만든 페이지 포함
        print("\n[4] page.list — after create")
        after = await client.pages.list()
        if not any(r.slug == slug for r in after):
            print(f"    !! created slug {slug!r} not in list")
            return 1
        print(f"    {len(after)} pages (was {len(before)}) — created slug found ✓")

        # 5. update
        print("\n[5] page.update — change content + structured")
        new_structured = {"milestones": [{"name": "M2"}], "in_scope": ["x", "y"]}
        updated = await client.pages.update(
            slug,
            PageUpdate(
                content_md="# Updated\n\nAfter update step.",
                structured=new_structured,
            ),
        )
        if updated is None:
            print("    !! update returned None")
            return 1
        if not updated.content_md.startswith("# Updated"):
            print(f"    !! content not updated: {updated.content_md[:60]!r}")
            return 1
        if updated.structured != new_structured:
            print(f"    !! structured not updated: {updated.structured}")
            return 1
        if updated.title != created.title:
            print(f"    !! title accidentally changed: {updated.title!r}")
            return 1
        print("    update OK (content + structured 변경, title 보존)")

        # 6. count
        print("\n[6] page.count")
        n = await client.pages.count()
        print(f"    {n} pages")

        # 7. delete (cleanup)
        print("\n[7] page.delete (cleanup)")
        ok = await client.pages.delete(slug)
        if not ok:
            print("    !! delete returned False")
            return 1
        # 사라졌는지 재조회
        gone = await client.pages.get(slug)
        if gone is not None:
            print("    !! page still present after delete")
            return 1
        print("    delete OK + post-delete get → None")

        print("\nALL PASS ✅")
        print(f"verification slug={slug} (deleted)")
        return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
